name: Manual Repo Sync

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Source repo name from org"
        required: true
        type: string

      target_repo:
        description: "Target repo name"
        required: true
        type: string

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Automation Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x scripts/sync_repo.sh

      - name: Run Repo Sync
        env:
          GITHUB_TOKEN: ${{ secrets.MAIN_GITHUB_TOKEN }}

          GIT_USER_NAME: sonu4gh
          GIT_USER_EMAIL: sji16865@gmail.com

        run: |
          scripts/sync_repo.sh \
          "${{ vars.ORG_NAME }}/${{ github.event.inputs.source_repo }}" \
          "${{ vars.USERNAME }}/${{ github.event.inputs.target_repo }}"

      - name: Commit Sync State
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add sync-state/

          if git diff --cached --quiet
          then
            echo "No sync-state changes to commit"
          else
            git commit -m "update sync state"

            git push
          fi

